data_paths:
  source_file : "data/input_data/template_data.xlsx" #Should correspond to your purchases file
  source_file_manual_correction: [] #[OPTIONAL] Leave empty if no manual correction needed
  target_file: 'data/carbon_database/Target_pre_processed_PER1p5_nacres_fe_database_v1-0-2023.xlsx' #Should  correspond to the database file 
  output_file : "data/results/template.xlsx" #Feel free to change it

columns:
  #Source data informations:
  automated_column_labeling: True
  date_column: [] #[OPTIONAL] Leave empty if automated_column_labeling set to True
  unit_column: []  #[OPTIONAL] Leave empty if automated_column_labeling set to True
  amount_column: []  #[OPTIONAL] Leave empty if automated_column_labeling set to True
  source_columns_to_embed: [] #[OPTIONAL] Leave empty if automated_column_labeling set to True
  source_columns_emphasis: [] #[OPTIONAL] Leave empty if no column to prioritize
  contextual_nb_columns: 1 #[OPTIONAL] Leave empty if automated_column_labeling set to False
  source_columns_to_translate: [] #[OPTIONAL] Leave empty if you don't want any translation
  source_confidential_column: [] #[OPTIONAL] Leave empty if no confidentiality (this is only used for automated column recognition)
  key_manual_column: "" #[OPTIONAL] Leave empty if no manual correction
  hierarchical_selection_column_name: "" #[OPTIONAL] Leave empty if no hirerarchical selection
  #Target data informations:
  target_columns_to_translate: [] #[OPTIONAL] Leave empty if you don't want any translation
  target_columns_to_embed: ["nacres.description.en", "useeio.description", "module", "category"]
  target_columns_emphasis: ["nacres.description.en"] #[OPTIONAL] Leave empty if you don't want any priorization
  emission_factor_column: "per1p5.ef.kg.co2e.per.euro"

  target_factor_finance: True
  target_columns_uncertainty: 'per1p5.uncertainty.attr.kg.co2e.per.euro'
  target_columns_80_uncertainty: 'per1p5.uncertainty.80pct.kg.co2e.per.euro'
  
  target_columns_to_keep: 
    - "nacres.code"
    - "method"
    - "per1p5.uncertainty.attr.kg.co2e.per.euro"
    - "per1p5.uncertainty.80pct.kg.co2e.per.euro"
    - "per1p5.ef.kg.co2e.per.euro" #[OPTIONAL]

currency_settings: #Leave blank if you do not want any change in money
  target_currency: "EUR" 
  target_inflation_year: "2019"
  target_currency_additional: "CHF" # [OPTIONAL] Just convert it, does not have implications in CO2e calculations
