data_paths:
  source_file : "data/input_data/template_data_physical.xlsx" #Should correspond to your purchases file
  source_file_manual_correction: [] #[OPTIONAL] Leave empty if no manual correction needed
  target_file: 'data/carbon_database/pre_processed Cut-off Cumulative LCIA v3.10.xlsx' #Should  correspond to the database file 
  output_file : "data/results/template_ecoinvent.xlsx" #Feel free to change it

columns:
  #Source data informations:
  automated_column_labeling: True
  date_column: [] #[OPTIONAL] Leave empty if automated_column_labeling set to True
  unit_column: []  #[OPTIONAL] Leave empty if automated_column_labeling set to True
  amount_column: []  #[OPTIONAL] Leave empty if automated_column_labeling set to True
  contextual_nb_columns: 1 #[OPTIONAL] Leave empty if automated_column_labeling set to False
  source_columns_to_embed: [] #[OPTIONAL] Leave empty if automated_column_labeling set to True
  source_columns_emphasis: [] #[OPTIONAL] Leave empty if no column to prioritize
  source_columns_to_translate: [] #[OPTIONAL] Leave empty if you don't want any translation
  source_confidential_column: [] #[OPTIONAL] Leave empty if no confidentiality (this is only used for automated column recognition)

  key_manual_column: "" #[OPTIONAL] Leave empty if no manual correction
  hierarchical_selection_column_name: "" #[OPTIONAL] Leave empty if no hirerarchical selection

  #Target data informations:
  target_columns_to_translate: [] #[OPTIONAL] Leave empty if you don't want any translation
  target_columns_to_embed: ["Activity Name"]
  target_columns_emphasis: [] #[OPTIONAL] Leave empty if you don't want any priorization
  target_factor_finance: False
  target_columns_uncertainty: []
  target_columns_80_uncertainty: []
  emission_factor_column: "kg CO2-Eq"

  
  target_columns_to_keep: 
    - "kg CO2-Eq"
    - "Reference Product Name"
    - "Activity UUID_Product UUID"
    - "Reference Product Unit"
    - "Geography" #[OPTIONAL]

currency_settings: 