data_paths:
  source_file : "data/input_data/achats_EPFL/Extraction lignes de commandes CATALYSE 2023.xlsx" #Should correspond to your purchases file
  source_file_manual_correction: "data/input_data/achats_EPFL/Extraction lignes de commandes CATALYSE 2023_manual_correction.xlsx" #[OPTIONAL] Leave empty if no manual correction needed
  target_file: 'data/carbon_database/Target_pre_processed_PER1p5_nacres_fe_database_v1-0-2023.xlsx' #Should  correspond to the database file 
  output_file : "data/results/EPFL_CO2_2023.xlsx" #Feel free to change it

columns:
  #Source data informations:
  automated_column_labeling: False
  date_column: "Date de commande" #[OPTIONAL] Leave empty if automated_column_labeling set to True
  unit_column: "Devise"  #[OPTIONAL] Leave empty if automated_column_labeling set to True
  amount_column: "Montant total"  #[OPTIONAL] Leave empty if automated_column_labeling set to True
  source_columns_to_embed: ["fam_dom_order", "fam_fam_order","fam_sfam_order", "fam_ssfam_order"]
  source_columns_emphasis: [] #[OPTIONAL] Leave empty if no column to prioritize
  source_columns_to_translate: [] #[OPTIONAL] Leave empty if you don't want any translation
  source_confidential_column: ["Libellé article"] #[OPTIONAL] Leave empty if no confidentiality (this is only used for automated column recognition)
  #Target data informations:
  target_columns_to_translate: [] #[OPTIONAL] Leave empty if you don't want any translation
  target_columns_to_embed: ["nacres.description.en", "useeio.description", "module", "category"]
  target_columns_emphasis: ["nacres.description.en"] #[OPTIONAL] Leave empty if you don't want any priorization
  emission_factor_column: "per1p5.ef.kg.co2e.per.euro"

  key_manual_column: "Libellé article" #[OPTIONAL] Leave empty if no manual correction
  hierarchical_selection_column_name: "Family" #[OPTIONAL] Leave empty if no hirerarchical selection
  
  target_columns_to_keep: 
    - "nacres.code"
    - "method"
    - "per1p5.uncertainty.attr.kg.co2e.per.euro"
    - "per1p5.uncertainty.80pct.kg.co2e.per.euro"
    - "per1p5.ef.kg.co2e.per.euro" #[OPTIONAL]

currency_settings: #Leave blank if you do not want any change in money
  target_currency: "EUR" 
  target_inflation_year: "2019"
  target_currency_additional: "CHF" # [OPTIONAL] Just convert it, does not have implications in CO2e calculations
